/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'kbglyph\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-twitter' : '&#xf099;',
			'icon-facebook' : '&#xf09a;',
			'icon-github' : '&#xf09b;',
			'icon-rss' : '&#xf09e;',
			'icon-linkedin-sign' : '&#xf08c;',
			'icon-globe' : '&#xf0ac;',
			'icon-remove-sign' : '&#xf057;',
			'icon-remove-circle' : '&#xf05c;',
			'icon-thumbs-down' : '&#xf088;',
			'icon-thumbs-up' : '&#xf087;',
			'icon-github-sign' : '&#xf092;',
			'icon-facebook-sign' : '&#xf082;',
			'icon-twitter-sign' : '&#xf081;',
			'icon-calendar' : '&#xf073;',
			'icon-bar-chart' : '&#xf080;',
			'icon-list-ul' : '&#xf0ca;',
			'icon-google-plus' : '&#xf0d5;',
			'icon-linkedin' : '&#xf0e1;',
			'icon-pinterest' : '&#xf0d2;',
			'icon-pinterest-sign' : '&#xf0d3;',
			'icon-google-plus-sign' : '&#xf0d4;',
			'icon-sitemap' : '&#xf0e8;',
			'icon-cloud-download' : '&#xf0ed;',
			'icon-cloud-upload' : '&#xf0ee;',
			'icon-quote-left' : '&#xf10d;',
			'icon-quote-right' : '&#xf10e;',
			'icon-mobile' : '&#xf10b;',
			'icon-tablet' : '&#xf10a;',
			'icon-laptop' : '&#xf109;',
			'icon-desktop' : '&#xf108;',
			'icon-double-angle-left' : '&#xf100;',
			'icon-double-angle-right' : '&#xf101;',
			'icon-double-angle-up' : '&#xf102;',
			'icon-double-angle-down' : '&#xf103;',
			'icon-angle-left' : '&#xf104;',
			'icon-angle-right' : '&#xf105;',
			'icon-angle-up' : '&#xf106;',
			'icon-angle-down' : '&#xf107;',
			'icon-caret-down' : '&#xf0d7;',
			'icon-caret-up' : '&#xf0d8;',
			'icon-caret-left' : '&#xf0d9;',
			'icon-caret-right' : '&#xf0da;',
			'icon-reorder' : '&#xf0c9;',
			'icon-signal' : '&#xf012;',
			'icon-th-list' : '&#xf00b;',
			'icon-ok' : '&#xf00c;',
			'icon-remove' : '&#xf00d;',
			'icon-star' : '&#xf005;',
			'icon-star-empty' : '&#xf006;',
			'icon-heart' : '&#xf004;',
			'icon-user' : '&#xf007;',
			'icon-comments-alt' : '&#xf0e6;',
			'icon-search' : '&#xf002;',
			'icon-envelope' : '&#xf003;',
			'icon-group' : '&#xf0c0;',
			'icon-shopping-cart' : '&#xf07a;',
			'icon-folder-close' : '&#xf07b;',
			'icon-folder-open' : '&#xf07c;',
			'icon-spinner' : '&#xf110;',
			'icon-wrench' : '&#xf0ad;',
			'icon-list' : '&#xe000;',
			'icon-list-2' : '&#xe001;',
			'icon-spinner-2' : '&#xe002;',
			'icon-vimeo2' : '&#xe003;',
			'icon-vimeo' : '&#xe004;',
			'icon-flickr' : '&#xe005;',
			'icon-flickr-2' : '&#xe006;',
			'icon-feed' : '&#xe007;',
			'icon-github-2' : '&#xe008;',
			'icon-github-3' : '&#xe009;',
			'icon-tumblr' : '&#xe00a;',
			'icon-tumblr-2' : '&#xe00b;',
			'icon-skype' : '&#xe00c;',
			'icon-apple' : '&#xe00d;',
			'icon-windows8' : '&#xe00e;',
			'icon-tux' : '&#xe00f;',
			'icon-foursquare' : '&#xe010;',
			'icon-foursquare-2' : '&#xe011;',
			'icon-yelp' : '&#xe012;',
			'icon-safari' : '&#xe013;',
			'icon-opera' : '&#xe014;',
			'icon-IE' : '&#xe015;',
			'icon-firefox' : '&#xe016;',
			'icon-chrome' : '&#xe017;',
			'icon-delicious' : '&#xe018;',
			'icon-stumbleupon' : '&#xe019;',
			'icon-lastfm' : '&#xe01a;',
			'icon-lastfm-2' : '&#xe01b;',
			'icon-blogger' : '&#xe01c;',
			'icon-blogger-2' : '&#xe01d;',
			'icon-dribbble' : '&#xe01f;',
			'icon-dribbble-2' : '&#xe01e;',
			'icon-home' : '&#xe020;',
			'icon-cloudy' : '&#xe023;',
			'icon-cloudy-2' : '&#xe024;',
			'icon-weather' : '&#xe025;',
			'icon-weather-2' : '&#xe026;',
			'icon-snowy' : '&#xe027;',
			'icon-snowy-2' : '&#xe028;',
			'icon-windy' : '&#xe029;',
			'icon-windy-2' : '&#xe02a;',
			'icon-rainy' : '&#xe02b;',
			'icon-rainy-2' : '&#xe02c;',
			'icon-cloud' : '&#xe02d;',
			'icon-cloud-2' : '&#xe02e;',
			'icon-cloud-3' : '&#xe02f;',
			'icon-cloud-4' : '&#xe030;',
			'icon-sun' : '&#xe031;',
			'icon-moon' : '&#xe032;',
			'icon-windy-3' : '&#xe021;',
			'icon-windy-4' : '&#xe034;',
			'icon-lightning' : '&#xe035;',
			'icon-lightning-2' : '&#xe036;',
			'icon-mail' : '&#xe038;',
			'icon-map-pin-fill' : '&#xe03b;',
			'icon-appstore' : '&#xe03c;',
			'icon-behanced' : '&#xe03d;',
			'icon-youtube' : '&#xe03e;',
			'icon-itunes' : '&#xe03f;',
			'icon-creativecommons' : '&#xe040;',
			'icon-dropbox' : '&#xe041;',
			'icon-delicious-2' : '&#xe042;',
			'icon-google_talk' : '&#xe043;',
			'icon-wordpress_alt' : '&#xe044;',
			'icon-wordpress' : '&#xe045;',
			'icon-paypal' : '&#xe046;',
			'icon-deviantart' : '&#xe047;',
			'icon-etsy' : '&#xe048;',
			'icon-vcard' : '&#xe04a;',
			'icon-kblogo-sm' : '&#xe04b;',
			'icon-lightbulb' : '&#xf0eb;',
			'icon-deviantart-2' : '&#xe04c;',
			'icon-html5' : '&#xe052;',
			'icon-css3' : '&#xe053;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};